---
- hosts: "ansible"
  tasks:
    - name: create docker image
      command: docker build -t regapp:latest .
      args:
        chdir: /opt/docker

    - name: tag docker image to push
      command: docker tag regapp:latest ngsharna/regapp:latest

    - name: push docker image
      command: docker push ngsharna/regapp:latest
